### ISSUE TITLE
works well with es6 imports in browser?

### ISSUE THREAD

**Issue by abhijithvijayan** [sindresorhus/crypto-random-string#11]

**Comment by sindresorhus** [comment]
It should work in the browser if you bundle it with Webpack or Rollup, but no guarantees. Or alternatively, depend on https://github.com/crypto-browserify/crypto-browserify

**Comment by abhijithvijayan** [comment]
> It should work in the browser if you bundle it with Webpack or Rollup, but no guarantees. Or alternatively, depend on https://github.com/crypto-browserify/crypto-browserify

I want to use in react-native. So it might work right?

**Comment by sidoshi** [comment]
I think it would be a good idea to add [randombytes](https://www.npmjs.com/package/randombytes) as a dependency instead of using `crypto.randomBytes`. That would make browser support first-class without any changes in bundler configuration.

**Comment by sidoshi** [comment]
I tried to check if all the tests pass and the library is compatible with node `crypto`.

See #12

**Comment by abhijithvijayan** [comment]
@sidoshi Thanks for noticing. So I guess I could use the https://github.com/crypto-browserify/randombytes
package directly instead of this package right?

**Comment by sidoshi** [comment]
@abhijitvijayan No, randombytes would be a dependency of this package to generate a random string.
