### ISSUE TITLE
Could you provide regex in the documentation for Url-Safe

### ISSUE THREAD

**Issue by hcbh96** [sindresorhus/crypto-random-string#13]
I wanted to check whether you guys might be able to provide a regex validation for the URL-Safe random generator?

I saw this in tests but it says probabilistic next to it so not sure if it is right ❓ 

`/^[a-zA-Z\d._~-]*$/`

**Comment by sindresorhus** [comment]
What’s your use-case?

**Comment by hcbh96** [comment]
Sorry for being slow on this - I was trying to do regex validation on an endpoint that used a url safe randomly generated url and I wanted to make sure the input url only contained valid chars

... I returned to using alphanum as I knew the validation schema and I also realised that the url-safe validation can fail for some of my use cases when the randomly generated string ends in a "."
