### ISSUE TITLE
Typescript build fails with version 3 of library.

### ISSUE THREAD

**Issue by BartolomeoItaliano** [sindresorhus/crypto-random-string#19]
Typescript build fails with following dependencies, if I use version 3 of library.

Package.json Important dependencies:
`{
  "devDependencies": {
    "@types/node": "~8.10.18",
    "ts-node": "^7.0.1",
    "tsutils": "~2.27.1",
    "typescript": "~2.9.1"
  },
  "dependencies": {
    "crypto-random-string": "^3.1.0",
    "tslib": "~1.9.2"
  }
}
`

Message I get:

> node_modules/type-fest/source/basic.d.ts:1:1 - error TS1084: Invalid 'reference' directive syntax.

> 1 /// \<reference lib="esnext"/\>

If I remove library from dependecies build passes succesfully.
If I switch to version 2.0.0 build also passes.

**Comment by sindresorhus** [comment]
You need to upgrade your TypeScript version.
