### ISSUE TITLE
Smaller set of dependencies

### ISSUE THREAD

**Issue by dimaqq** [sindresorhus/crypto-random-string#21]
It seems to me and PCMIIAW, that `require('crypto')` in `crypto-random-string/index.js` is responsible for webpack ultimately bundling a while lot of code, highlighted here:

<img width="1920" alt="crypto-random-string baggage" src="https://user-images.githubusercontent.com/662249/81248815-32154d00-9058-11ea-9598-2e7e4e933fde.png">

Here's the result of stubbing out this library:

```
> yarn build
...
File sizes after gzip:

  155.05 KB (-123.73 KB)  build/static/js/2.b6efb300.chunk.js
  49.11 KB (-469 B)       build/static/js/main.9d9f2002.chunk.js
  771 B                   build/static/js/runtime-main.212bc426.js
```

Given that this is a very focused library, could its impact on the bundle size be much smaller than `124KB gzipped`?

In my case I use it to generate a strong random token, but I don't use any other crypto.
(the server responds with something signed, but I don't have to validate the response).

**Comment by sindresorhus** [comment]
This package was mainly made for Node.js. While it does work in the browsers using shims, it's not my concern how large those turn out to be. When we can target Node.js 14 and use ESM modules, the size might improve as we could only import the `randomBytes` method, which would help for tree-shaking. Until then, I recommend finding another package for this if you need it in the browser.
