### ISSUE TITLE
Angular 9 : Module Not Found : can't resolve 'crypto' in node-modules/crypto-random-string

### ISSUE THREAD

**Issue by sudhakar-sekar** [sindresorhus/crypto-random-string#22]
Hi,

I am upgrading my angular application from v8 to v9. 
Am getting error while combiling in angular application, "Module Not Found : can't resolve 'crypto' in node-modules/crypto-random-string" on angular V9 only.

Node Js : v12.16.3
CLI : v9.1.5.
Typescript: v3.8.3

Anyone help me to resolve this issue ASAP.

Thanks,
Sudhakar Chandrasekaran.

**Comment by sindresorhus** [comment]
This is a problem with the Angular 9 build tool, not this package. Open an issue on Angular instead.

**Comment by sudhakar-sekar** [comment]
Ok. Thanks @sindresorhus
