### ISSUE TITLE
npm version outdated compared to master branch

### ISSUE THREAD

**Issue by niftylettuce** [sindresorhus/crypto-random-string#28]
see <https://github.com/sindresorhus/crypto-random-string/pull/27#issuecomment-683470566>

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/crypto-random-string/pull/27#issuecomment-683531653

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/crypto-random-string/releases/tag/v3.3.0
