### ISSUE TITLE
Length parameter is not working

### ISSUE THREAD

**Issue by mrafiqk** [sindresorhus/crypto-random-string#29]
I have provided `options = {length: 6, type: 'numeric'}` but my returned string length is not matched all the time. Some time it returned less than 6 character.
Kindly fix this
Thanks

**Comment by sindresorhus** [comment]
// @thekevinbrown

**Comment by mrafiqk** [comment]
@sindresorhus @thekevinbrown Any update?

**Comment by thekevinbrown** [comment]
@mrafiqk can you provide a reproduction for me?

**Comment by Richienb** [comment]
@mrafiqk Are you converting the resulting string to a number? If so, `012` (length of 3) becomes `12` (length of 2).

**Comment by mrafiqk** [comment]
@Richienb No, I didn't convert the resulting string to a number. I just append the returned string to my string.

**Comment by mrafiqk** [comment]
> @mrafiqk can you provide a reproduction for me?

I have tried the newest version. I am not able to replicate it. I don't know it really fixed or not

**Comment by thekevinbrown** [comment]
If you have a script which generates `numeric` random strings many times (like 50,000+), does it happen?

Basically the length of numerics is handled the same way as the length of the other strings this library can generate, so if there's a problem with `numeric` it's probably also happening with other strings, so we'd need to find a way to replicate it so we can ensure we fix it with any change we might make.

**Comment by sindresorhus** [comment]
Closing as this is not reproducible. I'm happy to reopen if someone submits a failing test.
