### ISSUE TITLE
TypeError on type:" ascii-printable"

### ISSUE THREAD

**Issue by tsarboot** [sindresorhus/crypto-random-string#32]
Working fine with other types but when i set it to  ascii-printable it raises a TypeError: Unknown type error , i copied the same example given in the README but the problem stays the same
`var re_id = cryptoRandomString({
                length: 10,
                type: "ascii-printable",
              });
`

**Comment by sindresorhus** [comment]
We have a test for this: https://github.com/sindresorhus/crypto-random-string/blob/98e54d259454598b753b88b3096321c308de66fb/test.js#L74 So you're probably on an older version.
