### ISSUE TITLE
Question: Is crypto-random-string processor intensive?

### ISSUE THREAD

**Issue by 333one** [sindresorhus/crypto-random-string#34]
I use crypto-random-string on my projects and I love it.

However I was wondering is this module processor intensive like hashing or is random string creation fairly easy on the processor?

**Comment by sindresorhus** [comment]
It should be pretty fast, but everything is relative, and in the end, it depends on how many times you call it in a second.

**Comment by 333one** [comment]
Awesome, great module thanks!
