### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/crypto-random-string#42]
I propose the following backends:

Node.js
- Sync: [crypto.randomBytes][randomBytes]
- Async: [crypto.randomBytes](randomBytes), ([crypto.webcrypto.getRandomValues](https://nodejs.org/api/webcrypto.html#cryptogetrandomvaluestypedarray) when targeting Node.js 16)

Browser
- Async: [crypto.getRandomValues](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues)

and this infrastructure:

- `browser.js` (randomness source) → `core.js`
- `index.js` (randomness source) → `core.js`

[randomBytes]: https://nodejs.org/api/crypto.html#cryptorandombytessize-callback
[getRandomValues]: https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues

**Comment by sindresorhus** [comment]
Sounds good
