### ISSUE TITLE
require() of ES modules is not supported

### ISSUE THREAD

**Issue by fullDev9233** [sindresorhus/crypto-random-string#48]
When I try to import this module(V5.0.0) using TypeScript, I am getting this error.
import cryptoRandomString from 'crypto-random-string';

`
Must use import to load ES Module: /Volumes/Work/Work/2023-03-06-Testverfahren/server/node_modules/crypto-random-string/index.js
require() of ES modules is not supported.
`

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
