### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by awongCM** [sindresorhus/crypto-random-string#49]
I'm running into problem when using Jest to import the library and run my tests.

I get the following:

```

    /Users/andywongcm/Documents/side-projects/transaction-otp-service-sls/node_modules/crypto-random-string/index.js:3
    import {promisify} from 'node:util';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import cryptoRandomString from "crypto-random-string";
        | ^
      2 |
      3 | const AWS = require('aws-sdk');
      4 |
```

Any advice you can provide on how to configure Jest to play with the crypto-random-string library nicely?

Thanks.

I also found someone posted this StackOverflow for the same symptom of the problem as mine.
https://stackoverflow.com/q/72447286/1065118
FYI

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by awongCM** [comment]
> https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

Thanks for the link.

I have actually read the link before - which is the reason that leads me here to raise this question, but for a different context.

Knowing the full extent that the latest library version comes with the _design intent_ of removing support for CommonJS support and in favour of ESM modules, along with the fact Jest has experimental support for the ESM environment, I decide to differ the use of this library until Jest makes the official announcement for its full ESM support.

I will go for something like `nanoid@3` that still has CommonJS compatibility for all of my NodeJS/Typescript unit testing needs.

Cheers.
